####
# Native
#
FROM quay.io/quarkus/centos-quarkus-maven:22.0-java11 AS builder

COPY . /project/
RUN ./mvnw clean package -Pnative

FROM quay.io/quarkus/quarkus-micro-image:1.0

WORKDIR /work/

RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --from=builder --chown=1001:root /project/target/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
